version: '3.9'

services:
  db:
    image: postgres:18.1
    container_name: earphone-review-db
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: earphone-review
    ports:
      - '5433:5432'
    volumes:
      - db-data:/var/lib/postgresql

volumes:
  db-data:
